### ISSUE TITLE
Publish task in Buidler plugin

### ISSUE THREAD

**Issue by ajsantander** [aragon/buidler-aragon#49] opened 2020-01-23 13:12 UTC
Migrate apm publishing from CLI to Buidler plugin.

Don't delete support in CLI yet. We want to let it sit in the plugin for a while before retracting the feature from the CLI.

**Comment by sohkai** [comment] 2020-03-19 16:10
Duplicate of #41.

**Closed by sohkai** 2020-03-19 16:10 UTC
